/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PorqueRouteImport } from './routes/porque'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AgentesCerneopsRouteImport } from './routes/agentes-cerneops'
import { Route as AcademiaRouteImport } from './routes/academia'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanosSlugRouteImport } from './routes/planos.$slug'
import { Route as AgentesSlugRouteImport } from './routes/agentes.$slug'
import { Route as ApiContactSupraRouteImport } from './routes/api/contact/supra'

const PorqueRoute = PorqueRouteImport.update({
  id: '/porque',
  path: '/porque',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesCerneopsRoute = AgentesCerneopsRouteImport.update({
  id: '/agentes-cerneops',
  path: '/agentes-cerneops',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiaRoute = AcademiaRouteImport.update({
  id: '/academia',
  path: '/academia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosSlugRoute = PlanosSlugRouteImport.update({
  id: '/planos/$slug',
  path: '/planos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesSlugRoute = AgentesSlugRouteImport.update({
  id: '/agentes/$slug',
  path: '/agentes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactSupraRoute = ApiContactSupraRouteImport.update({
  id: '/api/contact/supra',
  path: '/api/contact/supra',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/agentes-cerneops': typeof AgentesCerneopsRoute
  '/demo': typeof DemoRoute
  '/porque': typeof PorqueRoute
  '/agentes/$slug': typeof AgentesSlugRoute
  '/planos/$slug': typeof PlanosSlugRoute
  '/api/contact/supra': typeof ApiContactSupraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/agentes-cerneops': typeof AgentesCerneopsRoute
  '/demo': typeof DemoRoute
  '/porque': typeof PorqueRoute
  '/agentes/$slug': typeof AgentesSlugRoute
  '/planos/$slug': typeof PlanosSlugRoute
  '/api/contact/supra': typeof ApiContactSupraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/agentes-cerneops': typeof AgentesCerneopsRoute
  '/demo': typeof DemoRoute
  '/porque': typeof PorqueRoute
  '/agentes/$slug': typeof AgentesSlugRoute
  '/planos/$slug': typeof PlanosSlugRoute
  '/api/contact/supra': typeof ApiContactSupraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academia'
    | '/agentes-cerneops'
    | '/demo'
    | '/porque'
    | '/agentes/$slug'
    | '/planos/$slug'
    | '/api/contact/supra'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academia'
    | '/agentes-cerneops'
    | '/demo'
    | '/porque'
    | '/agentes/$slug'
    | '/planos/$slug'
    | '/api/contact/supra'
  id:
    | '__root__'
    | '/'
    | '/academia'
    | '/agentes-cerneops'
    | '/demo'
    | '/porque'
    | '/agentes/$slug'
    | '/planos/$slug'
    | '/api/contact/supra'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademiaRoute: typeof AcademiaRoute
  AgentesCerneopsRoute: typeof AgentesCerneopsRoute
  DemoRoute: typeof DemoRoute
  PorqueRoute: typeof PorqueRoute
  AgentesSlugRoute: typeof AgentesSlugRoute
  PlanosSlugRoute: typeof PlanosSlugRoute
  ApiContactSupraRoute: typeof ApiContactSupraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/porque': {
      id: '/porque'
      path: '/porque'
      fullPath: '/porque'
      preLoaderRoute: typeof PorqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes-cerneops': {
      id: '/agentes-cerneops'
      path: '/agentes-cerneops'
      fullPath: '/agentes-cerneops'
      preLoaderRoute: typeof AgentesCerneopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academia': {
      id: '/academia'
      path: '/academia'
      fullPath: '/academia'
      preLoaderRoute: typeof AcademiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos/$slug': {
      id: '/planos/$slug'
      path: '/planos/$slug'
      fullPath: '/planos/$slug'
      preLoaderRoute: typeof PlanosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes/$slug': {
      id: '/agentes/$slug'
      path: '/agentes/$slug'
      fullPath: '/agentes/$slug'
      preLoaderRoute: typeof AgentesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact/supra': {
      id: '/api/contact/supra'
      path: '/api/contact/supra'
      fullPath: '/api/contact/supra'
      preLoaderRoute: typeof ApiContactSupraRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademiaRoute: AcademiaRoute,
  AgentesCerneopsRoute: AgentesCerneopsRoute,
  DemoRoute: DemoRoute,
  PorqueRoute: PorqueRoute,
  AgentesSlugRoute: AgentesSlugRoute,
  PlanosSlugRoute: PlanosSlugRoute,
  ApiContactSupraRoute: ApiContactSupraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
